// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistencia.Context;

namespace Persistencia.Migrations
{
    [DbContext(typeof(EFContext))]
    [Migration("20190911144859_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Modelo.Entidades.DespesaFixa", b =>
                {
                    b.Property<int?>("DespesaFixaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Categoria");

                    b.Property<DateTime>("DataHora");

                    b.Property<string>("NomeItem");

                    b.Property<double>("Valor");

                    b.HasKey("DespesaFixaId");

                    b.ToTable("DESPESAS_FIXAS");
                });

            modelBuilder.Entity("Modelo.Entidades.DespesaMensal", b =>
                {
                    b.Property<int?>("DespesaMensalId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataHora");

                    b.Property<string>("NomeItem");

                    b.Property<double>("Valor");

                    b.HasKey("DespesaMensalId");

                    b.ToTable("DESPESAS_MENSAIS");
                });

            modelBuilder.Entity("Modelo.Entidades.DespesaParcelada", b =>
                {
                    b.Property<int>("DespesaParceladaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Categoria");

                    b.Property<DateTime>("DataHora");

                    b.Property<string>("NomeItem");

                    b.Property<int>("QuantidadeParcela");

                    b.Property<bool>("StatusPagamento");

                    b.Property<double>("Valor");

                    b.Property<double>("ValorParcela");

                    b.HasKey("DespesaParceladaId");

                    b.ToTable("DESPESAS_PARCELADAS");
                });
#pragma warning restore 612, 618
        }
    }
}
